# Generated by Django 5.2.8 on 2025-11-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback', '0002_feedback_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='categories',
        ),
    ]
